version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
    command: python main.py --api-only
    networks:
      - simulator-network
    # El healthcheck actual podría estar fallando si curl no está instalado o el endpoint no está listo
    # Usemos un healthcheck más simple basado en TCP
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.socket().connect((\"localhost\", 8000))"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      - API_HOST=api
      - API_PORT=8000
      - STREAMLIT_PORT=8501
    command: python main.py --ui-only --api-host api
    depends_on:
      api:
        condition: service_healthy
    networks:
      - simulator-network

networks:
  simulator-network:
    driver: bridge
