version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
    command: python main.py --api-only
    networks:
      - simulator-network

  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      - API_HOST=api
      - API_PORT=8000
      - STREAMLIT_PORT=8501
    command: python main.py --ui-only --api-host api
    depends_on:
      - api
    networks:
      - simulator-network

networks:
  simulator-network:
    driver: bridge
